[package]
name = "point-mass-ballistics"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.25.3"
ordered-float = "2.1.1"
lazy_static = "1.4.0"
typenum = "1.13.0"
num-traits = "0.2.14"
uom = "0.31.1"
