[package]
name = "ballistics"
version = "0.1.0"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]

[dependencies]
ndarray = "0.11"
ndarray-linalg = "0.9"

[[bin]]
name = "ballistics"
doc = false
