[package]
name = "rballistics-flat"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]

[dependencies]
nalgebra = "0.16"
new-ordered-float = "1.0"
custom_derive = "0.1"
enum_derive = "0.1"
