[package]
name = "point-mass-ballistics"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2021"

[dependencies]
nalgebra = "0.30.1"
ordered-float = "2.10.0"
lazy_static = "1.4.0"
typenum = "1.15.0"
num-traits = "0.2.14"
uom = "0.32.0"
