[package]
name = "point-mass-ballistics"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.19.0"
ordered-float = "1.0.2"
lazy_static = "1.4.0"
uom = "0.26.0"
