[package]
name = "point-mass-ballistics"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2021"

[dependencies]
nalgebra = "0.32.2"
num-traits = "0.2.15"
typenum = "1.16.0"
uom = "0.34.0"
