[package]
name = "point-mass-ballistics"
version = "0.0.1"
edition = "2024"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]

[dependencies]
uom = "0.37.0"

[dependencies.nalgebra]
version = "0.33.2"
default-features = false
features = ["std"]
