[package]
name = "point-mass-ballistics"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.22.1"
ordered-float = "2.0.0"
lazy_static = "1.4.0"
typenum = "1.12.0"
num-traits = "0.2.12"
uom = "0.29.0"
