[package]
name = "rballistics-flat"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nalgebra = "^0.16"
new-ordered-float = "^1.0"
approx = "^0.3"
# num = "0.2"
