[package]
name = "point-mass-ballistics"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nalgebra = "^0.18"
ordered-float = "^1.0"
# num = "0.2"
